### ISSUE TITLE
Network Disconnect when turning on mobile data.

### ISSUE THREAD

**Issue by BorjanEch0** [nextepc/nextepc#14]
Hi!

I manage to connect an UE to the network and everything works fine until i try to turn mobile data, at that point the connection drops immediately and keeps cycling between dropped and up non stop. In the logs it just keeps repeating:
Request
Response (accept)
Disconnect
Request
Response(acceot)....
and so on.
Edit: the only log i see error is this in pgwd:

WARN: Unknown PCO ID:(0x5) (pgw_s5c_build.c:668)

But the packet capture shows differently!
I do not know what to make of it. There is an error of reject and unknown UE but i can not seem to see the cause of the problem.
Please help me understand the packet capture.
Thank you.

[caploss.zip](https://github.com/open5gs/open5gs/files/3963116/caploss.zip)

**Comment by nextepc** [comment]
According to your S1 capture, the eNodeB sent Initial Context Setup Failure with unknown reason (Radio-network cause = unspecified). You may need to check some logs from the eNode to understand what parameter is not acceptable, since this is a response of Initial Context Setup Request sent by NextEPC.

**Comment by BorjanEch0** [comment]
Issue was very strange but fixed.

Issue was:

MNC in cell QCI\QoS was set different from served PLMN.
Now resolved.
